'use client';
import { useEffect,useRef,useState } from 'react';import { Button } from '@/components/ui/button';import { DESTINATIONS, UserRecord, parseQr } from '@/lib/users';import { useSpeech } from '@/hooks/useSpeech';import { tone } from '@/lib/sounds-client';
type State='HOME'|'SCANNING'|'LOCATION_SELECTION'|'PROCESSING'|'RESULT'|'RESET';type Result={result:'GRANTED'|'DENIED';reason:string;user:UserRecord;location:string};
export default function Page(){const speak=useSpeech();const [state,setState]=useState<State>('HOME');const [offline,setOffline]=useState(false);const [user,setUser]=useState<UserRecord|null>(null);const [qr,setQr]=useState('');const [result,setResult]=useState<Result|null>(null);const [admin,setAdmin]=useState(false);const [logs,setLogs]=useState<any[]>([]);const [checks,setChecks]=useState<any>({});const scanner=useRef<any>(null);const [cameraId,setCameraId]=useState('');const [cameras,setCameras]=useState<any[]>([]);
useEffect(()=>{speak('QR Access Kiosk ready.');fetch('/api/event',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({eventType:'startup',body:'QR Access Kiosk ready.'})}).catch(()=>{});fetch('/api/diagnostics').then(r=>r.json()).then(j=>setChecks(j.checks)).catch(()=>{});},[]);
function reset(){try{window.speechSynthesis.cancel();scanner.current?.stop?.()}catch{}setUser(null);setQr('');setResult(null);setState('HOME')}
async function start(){if(offline)return;speak('Please scan your identification QR code.');setState('SCANNING');setTimeout(async()=>{try{const mod=await import('html5-qrcode');const cams=await mod.Html5Qrcode.getCameras();setCameras(cams);const id=cameraId||cams[0]?.id;if(!id)throw new Error('no camera');const h=new mod.Html5Qrcode('reader');scanner.current=h;await h.start(id,{fps:10,qrbox:{width:320,height:320}},(decoded)=>onScan(decoded),()=>{});}catch{tone('failure');speak('Camera not available.');fetch('/api/event',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({eventType:'camera failure',body:'Camera not available.'})}).catch(()=>{});setTimeout(reset,1200)}},100)}
function onScan(decoded:string){try{scanner.current?.stop?.()}catch{}tone('scan');const p=parseQr(decoded);if(!p.ok){tone('failure');speak(p.reason);setTimeout(reset,1400);return}setQr(decoded);setUser(p.user);speak(`Welcome, ${p.user.name}. Please select a destination.`);setState('LOCATION_SELECTION')}
async function choose(location:string){if(!user){speak('Invalid QR code scanned.');return reset()}speak(`${location} selected.`);setState('PROCESSING');setTimeout(async()=>{try{const r=await fetch('/api/access',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({qr,location})});const j=await r.json();if(!j.ok)throw new Error(j.error);setResult(j);tone(j.result==='GRANTED'?'success':'failure');speak(j.result==='GRANTED'?`${j.user.name}, ${j.user.role}. ID number ${j.user.id}. Location access granted to ${j.location}.`:`${j.user.name}, access denied. ${j.reason}.`);setState('RESULT');setTimeout(()=>{setState('RESET');reset()},2000)}catch(e:any){tone('failure');speak(e.message||'Invalid location selected.');reset()}},500)}
async function login(){const password=prompt('Administrator password')||'';const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});if(r.ok){setAdmin(true);speak('Administrator access granted.');loadLogs()}}
async function loadLogs(){const j=await fetch('/api/logs').then(r=>r.json()).catch(()=>({logs:[]}));setLogs(j.logs||[])}
async function diag(){const j=await fetch('/api/diagnostics').then(r=>r.json());setChecks({...j.checks,Camera:navigator.mediaDevices?'PASS':'FAIL',Speech:'speechSynthesis'in window?'PASS':'FAIL'});}
if(offline)return <main className="min-h-screen bg-black text-white flex flex-col items-center justify-center gap-8"><h1 className="text-7xl font-black">SYSTEM OFFLINE</h1><Button onClick={()=>{setOffline(false);speak('System online.')}} className="bg-green-600 text-3xl">REACTIVATE</Button></main>;
if(state==='SCANNING')return <main className="min-h-screen bg-black text-white relative flex flex-col items-center justify-center"><div id="reader" className="w-full max-w-3xl"/><div className="absolute w-80 h-80 border-8 border-white rounded-3xl scan-mask pointer-events-none"/><h1 className="absolute top-10 text-5xl font-black">Scan your ID QR code</h1><Button onClick={reset} className="absolute bottom-8 bg-red-700">CANCEL</Button></main>;
if(state==='LOCATION_SELECTION'&&user)return <main className="min-h-screen bg-blue-950 text-white p-8 flex flex-col items-center"><h1 className="text-5xl font-black text-center">Welcome,<br/>{user.name}</h1><p className="text-4xl my-8">Where would you like to go?</p><div className="grid md:grid-cols-2 gap-6 w-full max-w-5xl">{DESTINATIONS.map(d=><Button key={d} onClick={()=>choose(d)} className="bg-white text-blue-950 text-4xl min-h-32">{d}</Button>)}</div></main>;
if(state==='PROCESSING')return <main className="min-h-screen bg-slate-900/90 text-white flex items-center justify-center"><h1 className="text-7xl font-black animate-pulse">PROCESSING...</h1></main>;
if(state==='RESULT'&&result)return <main className={`min-h-screen text-white flex flex-col items-center justify-center gap-5 ${result.result==='GRANTED'?'bg-green-950':'bg-red-950'}`}><h1 className="text-8xl font-black">ACCESS {result.result}</h1><div className="text-4xl text-center"><p>{result.user.name}</p>{result.result==='GRANTED'&&<><p>{result.user.role}</p><p>{result.user.department}</p><p>ID Number {result.user.id}</p></>}<p>{result.location}</p>{result.reason&&<p>{result.reason}</p>}</div></main>;
return <main className="min-h-screen bg-slate-100 dark:bg-slate-950 text-slate-950 dark:text-white p-8"><section className="max-w-5xl mx-auto min-h-[80vh] flex flex-col items-center justify-center gap-8"><h1 className="text-6xl font-black">QR Access Kiosk</h1><Button onClick={start} className="bg-blue-700 text-white text-7xl px-16 py-16 w-full max-w-4xl">START SCAN</Button><div className="flex flex-wrap gap-4 justify-center"><Button onClick={login} className="bg-slate-800 text-white text-2xl">ADMIN MENU</Button><Button onClick={diag} className="bg-slate-700 text-white text-2xl">DIAGNOSTICS</Button><Button onClick={()=>alert('QR Access Kiosk browser-based access terminal.')} className="bg-slate-700 text-white text-2xl">ABOUT</Button></div><p className="text-3xl font-bold">System Status: READY</p>{admin&&<aside className="w-full bg-white dark:bg-slate-900 rounded-3xl p-6 shadow space-y-4"><h2 className="text-4xl font-black">Admin Panel</h2><div className="flex flex-wrap gap-3"><Button onClick={loadLogs} className="bg-blue-600 text-white">View Logs</Button><Button onClick={()=>loadLogs()} className="bg-blue-600 text-white">Search/Filter Logs</Button><Button onClick={diag} className="bg-blue-600 text-white">Diagnostics</Button><Button onClick={()=>document.documentElement.classList.toggle('dark')} className="bg-blue-600 text-white">Theme Toggle</Button><Button onClick={reset} className="bg-orange-600 text-white">Reset System</Button><Button onClick={()=>{setOffline(true);speak('System entering offline mode.');fetch('/api/event',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({eventType:'shutdown',body:'System entering offline mode.'})}).catch(()=>{})}} className="bg-red-700 text-white">Shutdown Mode</Button><Button onClick={()=>fetch('/api/email/test',{method:'POST'})} className="bg-green-700 text-white">Send Test Email</Button><Button onClick={()=>{setAdmin(false);fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})})}} className="bg-slate-600 text-white">Logout</Button></div><label>Camera Selector <select value={cameraId} onChange={e=>setCameraId(e.target.value)} className="text-black p-2">{cameras.map(c=><option key={c.id} value={c.id}>{c.label||c.id}</option>)}</select></label><div className="grid grid-cols-2 md:grid-cols-3 gap-2">{Object.entries(checks).map(([k,v])=><div key={k} className="p-3 rounded bg-slate-200 dark:bg-slate-800">{k}: {String(v)}</div>)}</div><pre className="max-h-80 overflow-auto bg-black text-green-300 p-4 rounded">{logs.map(l=>`#${l.id} ${l.timestamp} ${l.eventType}\n${l.body}`).join('\n\n')}</pre></aside>}</section></main>}
